# Generated by Django 5.2.7 on 2025-10-15 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entidade', models.CharField(choices=[('substituicao', 'Substituição'), ('escala', 'Escala')], max_length=50)),
                ('id_entidade', models.IntegerField()),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('editado', 'Editado')], max_length=50)),
                ('usuario', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Função no Plantão')),
            ],
            options={
                'verbose_name_plural': 'Funções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Local de Trabalho')),
            ],
            options={
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(choices=[('Médico', 'Médico'), ('Médica', 'Médica'), ('Enfermeiro', 'Enfermeiro(a)'), ('Enfermeira', 'Enfermeira'), ('Técnico de Enfermagem', 'Técnico(a) de Enfermagem')], max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Profissionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes_necessarios', to='escala_app.funcao')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes_alocados', to='escala_app.local')),
            ],
            options={
                'verbose_name_plural': 'Plantões',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('substituida', 'Substituída'), ('cancelada', 'Cancelada')], default='ativo', max_length=50)),
                ('data_alocacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala_app.plantao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas_atribuidas', to='escala_app.profissional')),
            ],
            options={
                'verbose_name_plural': 'Escalas',
                'unique_together': {('plantao', 'profissional')},
            },
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='pendente', max_length=50)),
                ('escala_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituicao_solicitada', to='escala_app.escala')),
                ('profissional_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_saida', to='escala_app.profissional')),
                ('profissional_substituto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_entrada', to='escala_app.profissional')),
            ],
            options={
                'verbose_name_plural': 'Substituições',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
