# Generated by Django 5.2.7 on 2025-10-14 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=50)),
                ('id_entidade', models.IntegerField()),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('aprovado', 'Aprovado'), ('excluido', 'Excluído'), ('alterado', 'Alterado')], max_length=20)),
                ('usuario', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Auditorias',
            },
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('id_funcao', models.IntegerField()),
                ('id_local', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Plantões',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('carga_horaria_maxima_semanal', models.IntegerField(default=40)),
            ],
            options={
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo (Alocado)'), ('substituido', 'Substituído'), ('solicit_subst', 'Solicitando Substituição')], default='ativo', max_length=20)),
                ('data_alocacao', models.DateTimeField(auto_now_add=True)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='escala_app.plantao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='escala_app.profissional')),
            ],
            options={
                'verbose_name_plural': 'Escalas',
                'unique_together': {('plantao', 'profissional')},
            },
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=15)),
                ('aprovada_por_supervisor', models.BooleanField(default=False)),
                ('escala_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicao_original', to='escala_app.escala')),
                ('profissional_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_solicitadas', to='escala_app.profissional')),
                ('profissional_substituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituicoes_realizadas', to='escala_app.profissional')),
            ],
            options={
                'verbose_name_plural': 'Substituições',
            },
        ),
    ]
