# Generated by Django 5.2.7 on 2025-10-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=100)),
                ('id_entidade', models.IntegerField()),
                ('acao', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('carga_horaria_maxima_semanal', models.IntegerField(default=40)),
            ],
            options={
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala360.funcao')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala360.local')),
            ],
            options={
                'verbose_name_plural': 'Plantões',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('substituido', 'Substituído')], default='ativo', max_length=20)),
                ('data_alocacao', models.DateTimeField(auto_now_add=True)),
                ('id_plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala360.plantao')),
                ('id_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala360.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('id_escala_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_originais', to='escala360.escala')),
                ('id_profissional_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_solicitadas', to='escala360.profissional')),
                ('id_profissional_substituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_substituidas', to='escala360.profissional')),
            ],
            options={
                'verbose_name_plural': 'Substituições',
            },
        ),
    ]
